CREATE TYPE USER_PROFILE_TYPE AS (
    USER_ID                  INTEGER,
    USER_FIRST_NAME          VARCHAR(50),
    USER_LAST_NAME           VARCHAR(50),
    USER_EMAIL               VARCHAR(100),
    USER_PASSWORD_HASH       VARCHAR(255),
    USER_PROFILE_PICTURE     VARCHAR(255),
    USER_SIGNUP_DATETIME     TIMESTAMP,
    USER_LAST_LOGIN_DATETIME TIMESTAMP
);

CREATE OR REPLACE FUNCTION FN_VALIDATE_LOGIN (
    _USER_EMAIL VARCHAR(100)
)
RETURNS USER_PROFILE_TYPE
LANGUAGE plpgsql
AS $$
    DECLARE MATCHED_USER_PROFILE USER_PROFILE_TYPE;
    BEGIN
        MATCHED_USER_PROFILE.user_id = -1;

        SELECT *
        INTO MATCHED_USER_PROFILE
        FROM USERS
        WHERE _USER_EMAIL = USERS.user_email
        LIMIT 1;

        RETURN MATCHED_USER_PROFILE;
    END;
$$;

SELECT * FROM USERS;