CREATE OR REPLACE PROCEDURE SP_GET_PGRIDS_LIST (
    _USER_ID INTEGER,
    INOUT result_set REFCURSOR  -- Add an INOUT parameter for the cursor
)
LANGUAGE plpgsql
AS $$
    DECLARE
BEGIN
    OPEN result_set FOR
        WITH PPOOL_COUNT_CTE AS (
            SELECT PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID,
                   COUNT(PPOOL_ID) AS PPOOL_COUNT
            FROM PPOOLS
            GROUP BY PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID
        ),
        PNODE_COUNT_CTE AS (
            SELECT PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID,
                   COUNT(PNODES.PNODE_ID) AS PNODE_COUNT
            FROM PNODES
                RIGHT JOIN PPOOLS ON PPOOLS.PPOOL_ID = PNODES.PNODE_ASSOCIATED_PPOOL_ID
            GROUP BY PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID
        )
        (
            (
                SELECT PGRIDS.PGRID_ID,
                       PGRIDS.PGRID_NAME,
                       COALESCE(PPOOL_COUNT_CTE.PPOOL_COUNT, 0) AS PPOOL_COUNT,
                       COALESCE(PNODE_COUNT_CTE.PNODE_COUNT, 0) AS PNODE_COUNT
                FROM PGRIDS
                    LEFT JOIN PPOOL_COUNT_CTE ON PPOOL_COUNT_CTE.PPOOL_ASSOCIATERD_PGRID_ID = PGRIDS.PGRID_ID
                    LEFT JOIN PNODE_COUNT_CTE ON PNODE_COUNT_CTE.PPOOL_ASSOCIATERD_PGRID_ID = PGRIDS.PGRID_ID
                WHERE PGRIDS.pgrid_owner_id = _USER_ID
                ORDER BY pgrids.PGRID_ID
            )
            UNION
            (
                SELECT access_policy_pgrid_id,
                       PGRIDS.pgrid_name,
                       COALESCE(PPOOL_COUNT_CTE.PPOOL_COUNT, 0) AS PPOOL_COUNT,
                       COALESCE(PNODE_COUNT_CTE.PNODE_COUNT, 0) AS PNODE_COUNT
                FROM pgrid_access_policies
                    LEFT JOIN PPOOL_COUNT_CTE ON PPOOL_COUNT_CTE.PPOOL_ASSOCIATERD_PGRID_ID = pgrid_access_policies.access_policy_pgrid_id
                    LEFT JOIN PNODE_COUNT_CTE ON PNODE_COUNT_CTE.PPOOL_ASSOCIATERD_PGRID_ID = pgrid_access_policies.access_policy_pgrid_id
                    INNER JOIN PGRIDS ON pgrid_id = pgrid_access_policies.access_policy_pgrid_id
                WHERE access_policy_target_user_id = _USER_ID
            )
        );
    END;
$$;

CREATE OR REPLACE PROCEDURE SP_GET_PGRID_FULL_INFO (
    _targetPgridID INTEGER,
    INOUT result_set REFCURSOR  -- Add an INOUT parameter for the cursor
)
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        OPEN result_set FOR
            WITH PPOOL_COUNT_CTE AS (
                    SELECT PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID,
                           COUNT(PPOOL_ID) AS PPOOL_COUNT
                    FROM PPOOLS
                    GROUP BY PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID),
                PNODE_COUNT_CTE AS (
                    SELECT PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID,
                           COUNT(PNODES.PNODE_ID) AS PNODE_COUNT
                    FROM PNODES
                        RIGHT JOIN PPOOLS ON PPOOLS.PPOOL_ID = PNODES.PNODE_ASSOCIATED_PPOOL_ID -- THE RIGHT JOIN IS USED TO FORCE THE QUERY TO COUNT THE NUMBER OF PNODES FOR ALL PPOOLS, EVEN THOSE WITH 0 PNODES (IF WE USED INNER JOIN, IT WOULD DISCARD THE PPOOLS WITHOUT ANY PNODE => THEY DO NOT MAKE PART OF THE INTERSECTION OF THE TABLES)
                    GROUP BY PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID),
                ACTIVE_PNODE_COUNT_CTE AS (
                    SELECT PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID,
                           COUNT(PNODES.PNODE_ID) AS ACTIVE_PNODE_COUNT
                    FROM PNODES
                        INNER JOIN PNODE_STATUS ON PNODE_STATUS.PNODE_STATUS_ID = PNODES.PNODE_STATUS_ID
                        RIGHT JOIN PPOOLS ON PPOOLS.PPOOL_ID = PNODES.PNODE_ASSOCIATED_PPOOL_ID -- THE RIGHT JOIN IS USED TO FORCE THE QUERY TO COUNT THE NUMBER OF PNODES FOR ALL PPOOLS, EVEN THOSE WITH 0 PNODES (IF WE USED INNER JOIN, IT WOULD DISCARD THE PPOOLS WITHOUT ANY PNODE => THEY DO NOT MAKE PART OF THE INTERSECTION OF THE TABLES)
                    WHERE PNODE_STATUS.PNODE_STATUS_NAME = 'ACTIVE'
                    GROUP BY PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID)
            SELECT PGRIDS.PGRID_ID,
                   PGRIDS.PGRID_NAME,
                   PGRIDS.PGRID_CREATION_DATETIME,
                   PGRIDS.PGRID_LAST_UPDATE_DATETIME,
                   (USERS.USER_FIRST_NAME || ' ' || USERS.USER_LAST_NAME) AS PGRID_OWNER_FULL_NAME,
                   PGRIDS.PGRID_README_TEXT,
                   COALESCE(PPOOL_COUNT_CTE.PPOOL_COUNT, 0),
                   COALESCE(PNODE_COUNT_CTE.PNODE_COUNT, 0),
                   COALESCE(ACTIVE_PNODE_COUNT_CTE.ACTIVE_PNODE_COUNT, 0)
            FROM PGRIDS
                INNER JOIN PPOOL_COUNT_CTE ON PPOOL_COUNT_CTE.PPOOL_ASSOCIATERD_PGRID_ID = PGRIDS.PGRID_ID
                INNER JOIN PNODE_COUNT_CTE ON PNODE_COUNT_CTE.PPOOL_ASSOCIATERD_PGRID_ID = PGRIDS.PGRID_ID
                LEFT JOIN ACTIVE_PNODE_COUNT_CTE ON ACTIVE_PNODE_COUNT_CTE.PPOOL_ASSOCIATERD_PGRID_ID = PGRIDS.PGRID_ID
                INNER JOIN USERS ON USERS.USER_ID = PGRIDS.PGRID_OWNER_ID
            WHERE PGRIDS.PGRID_ID = _targetPgridID;
    END;
$$;

CREATE OR REPLACE PROCEDURE SP_GET_PGRID_ACCESSPOLICIES (
    _targetPgridID INTEGER,
    INOUT result_set REFCURSOR  -- Add an INOUT parameter for the cursor
)
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        OPEN result_set FOR
            SELECT PGRID_ACCESS_POLICIES.ACCESS_POLICY_ID,
                   PGRID_ACCESS_POLICIES.ACCESS_POLICY_NAME,
                   PGRIDS.PGRID_NAME,
                   USERS.USER_FIRST_NAME,
                   USERS.USER_LAST_NAME,
                   PGRID_ACCESS_POLICIES.ACCESS_POLICY_CREATION_DATETIME,
                   PGRID_ACCESS_POLICIES.ACCESS_POLICY_LAST_UPDATE_DATETIME,
                   PERMISSION_LEVELS.PERMISSION_LEVEL_NAME
            FROM PGRID_ACCESS_POLICIES
                     INNER JOIN PGRIDS ON PGRIDS.PGRID_ID = PGRID_ACCESS_POLICIES.ACCESS_POLICY_PGRID_ID
                     INNER JOIN USERS ON USERS.USER_ID = PGRID_ACCESS_POLICIES.ACCESS_POLICY_TARGET_USER_ID
                     INNER JOIN PERMISSION_LEVELS ON PERMISSION_LEVELS.PERMISSION_LEVEL_ID =
                                                     PGRID_ACCESS_POLICIES.ACCESS_POLICY_PERMISSION_LEVEL_ID
            WHERE PGRID_ACCESS_POLICIES.ACCESS_POLICY_PGRID_ID = _targetPgridID
            LIMIT 20;
    END;
$$;

CREATE OR REPLACE PROCEDURE SP_GET_PGRID_ACCESSAUDITS (
    _targetPgridID INTEGER,
    INOUT result_set REFCURSOR  -- Add an INOUT parameter for the cursor
)
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        OPEN result_set FOR
            SELECT
                PGRID_ACCESS_AUDITS.PGRID_AUDIT_ID,
                PGRID_ACCESS_AUDITS.PGRID_AUDIT_DATETIME,
                USERS.USER_FIRST_NAME,
                USERS.USER_LAST_NAME,
                PGRIDS.PGRID_NAME
            FROM PGRID_ACCESS_AUDITS
                INNER JOIN USERS ON PGRID_ACCESS_AUDITS.PGRID_AUDIT_ACTION_USER_ID = USERS.USER_ID
                INNER JOIN PGRIDS ON PGRID_ACCESS_AUDITS.PGRID_AUDIT_TARGET_PGRID_ID = PGRIDS.PGRID_ID
            WHERE PGRID_ACCESS_AUDITS.PGRID_AUDIT_TARGET_PGRID_ID = _targetPgridID
            LIMIT 10;
    END;
$$;

CREATE OR REPLACE PROCEDURE SP_GET_PGRID_PNODES_LOGINAUDITS (
    _targetPgridID INTEGER,
    INOUT result_set REFCURSOR  -- Add an INOUT parameter for the cursor
)
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        OPEN result_set FOR
            SELECT NODES_LOGIN_AUDITS.PNODE_LOGIN_AUDIT_ID,
                   NODES_LOGIN_AUDITS.PNODE_LOGIN_AUDIT_FSP_USER,
                   NODES_LOGIN_AUDITS.PNODE_LOGIN_AUDIT_DATETIME,
                   PNODE_LOGIN_STATUS.PNODE_LOGIN_STATUS_NAME,
                   NODES_LOGIN_AUDITS.PNODE_LOGIN_AUDIT_LOCATION,
                   PNODES.PNODE_NICKNAME,
                   PPOOLS.PPOOL_NAME
            FROM NODES_LOGIN_AUDITS
                INNER JOIN PNODE_LOGIN_STATUS ON NODES_LOGIN_AUDITS.PNODE_LOGIN_AUDIT_STATUS_ID = PNODE_LOGIN_STATUS.PNODE_LOGIN_STATUS_ID
                INNER JOIN PNODES ON NODES_LOGIN_AUDITS.PNODE_LOGIN_AUDIT_TARGET_PNODE_ID = PNODES.PNODE_ID
                INNER JOIN PPOOLS ON PNODES.PNODE_ASSOCIATED_PPOOL_ID = PPOOLS.PPOOL_ID
                INNER JOIN PGRIDS ON PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID = PGRIDS.PGRID_ID
            WHERE PGRIDS.PGRID_ID = _targetPgridID
            LIMIT 10;
    END;
$$;

CREATE OR REPLACE PROCEDURE SP_GET_PGRID_ERROR_LOGS (
    _targetPgridID INTEGER,
    INOUT result_set REFCURSOR  -- Add an INOUT parameter for the cursor
)
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        OPEN result_set FOR
            SELECT PNODES_FSP_ERROR_LOGS.ERROR_LOG_FSP_ID,
                   PNODES_FSP_ERROR_LOGS.ERROR_LOG_DATETIME,
                   PNODES_FSP_ERROR_LOGS.ERROR_LOG_DRIVER_NAME,
                   PNODES_FSP_ERROR_LOGS.ERROR_LOG_SUBSYSTEM,
                   PNODES_FSP_ERROR_LOGS.ERROR_LOG_RAW_DATA,
                   PNODES_FSP_ERROR_LOGS.ERROR_LOG_EVENT_SEVERITY,
                   PNODES_FSP_ERROR_LOGS.ERROR_LOG_ACTION_FLAGS,
                   PNODES_FSP_ERROR_LOGS.ERROR_LOG_ACTION_STATUS,
                   PNODES_FSP_ERROR_LOGS.ERROR_LOG_REFERENCE_CODE,
                   PNODES.PNODE_NICKNAME,
                   PPOOLS.PPOOL_NAME
            FROM PNODES_FSP_ERROR_LOGS
                     INNER JOIN PNODES ON PNODES_FSP_ERROR_LOGS.ERROR_LOG_SOURCE_PNODE_ID = PNODES.PNODE_ID
                     INNER JOIN PPOOLS ON PNODES.PNODE_ASSOCIATED_PPOOL_ID = PPOOLS.PPOOL_ID
                     INNER JOIN PGRIDS ON PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID = PGRIDS.PGRID_ID
            WHERE PGRIDS.PGRID_ID = _targetPgridID
            LIMIT 10;
    END;
$$;

CREATE OR REPLACE PROCEDURE SP_GET_PGRID_ATTENTIONLED_PNODES (
    _targetPgridID INTEGER,
    INOUT result_set REFCURSOR  -- Add an INOUT parameter for the cursor
)
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        OPEN result_set FOR
            SELECT PNODES.PNODE_NICKNAME,
                   PPOOLS.PPOOL_NAME
            FROM PNODES
                     INNER JOIN PPOOLS ON PNODES.PNODE_ASSOCIATED_PPOOL_ID = PPOOLS.PPOOL_ID
                     INNER JOIN PGRIDS ON PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID = PGRIDS.PGRID_ID
            WHERE PGRIDS.PGRID_ID = _targetPgridID AND PNODES.PANODE_ATTENTION_LED_STATE = 'ON'
            LIMIT 20;
    END;
$$;

CREATE OR REPLACE PROCEDURE SP_GET_PGRIDS_PPOOLS_LIST (
    _targetPgridID INTEGER,
    INOUT result_set REFCURSOR  -- Add an INOUT parameter for the cursor
)
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        OPEN result_set FOR
            WITH PNODES_COUNT_CTE AS (
                SELECT PNODE_ASSOCIATED_PPOOL_ID,
                       COUNT(PNODE_ID) AS PNODES_COUNT
                FROM PNODES
                GROUP BY PNODE_ASSOCIATED_PPOOL_ID
            )
            SELECT PPOOLS.PPOOL_ID,
                   PPOOLS.PPOOL_NAME,
                   COALESCE(PNODES_COUNT_CTE.PNODES_COUNT, 0) AS PNODE_COUNT
            FROM PPOOLS
                LEFT JOIN PNODES_COUNT_CTE ON PNODES_COUNT_CTE.PNODE_ASSOCIATED_PPOOL_ID = PPOOLS.PPOOL_ID
            WHERE PPOOLS.PPOOL_ASSOCIATERD_PGRID_ID = _targetPgridID
            ORDER BY PPOOLS.PPOOL_ID ASC;
    END;
$$;