CREATE TABLE GLOBAL_EVENT_SEVERITY (
    GLOBAL_EVENT_SEVERITY_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GLOBAL_EVENT_SEVERITY_NAME VARCHAR(50)
);

CREATE TABLE GLOBAL_EVENTS (
    GLOBAL_EVENT_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GLOBAL_EVENT_SEVERITY_LEVEL_ID INTEGER REFERENCES GLOBAL_EVENT_SEVERITY(GLOBAL_EVENT_SEVERITY_ID),
    GLOBAL_EVENT_TITLE VARCHAR(100),
    GLOBAL_EVENT_DESCRIPTION TEXT,
    GLOBAL_EVENT_TRIGGERED_AT TIMESTAMP DEFAULT NOW()
);

CREATE TABLE GLOBAL_EVENT_SINGLE_OPERATION_LINK (
    GLOBAL_EVENT_SINGLE_OPERATION_LINK_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GLOBAL_EVENT_ID INTEGER REFERENCES GLOBAL_EVENTS(GLOBAL_EVENT_ID),
    SINGLE_OPERATION_ID INTEGER REFERENCES PNODE_OPERATIONS(PNODE_OPERATION_ID)
);

CREATE TABLE GLOBAL_EVENT_BATCH_OPERATION_LINK (
    GLOBAL_EVENT_BATCH_OPERATION_LINK_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GLOBAL_EVENT_ID INTEGER REFERENCES GLOBAL_EVENTS(GLOBAL_EVENT_ID),
    BATCH_OPERATION_ID INTEGER REFERENCES PPOOLS_BATCH_OPERATIONS(BATCH_OPERATION_ID)
);

CREATE TABLE GLOBAL_EVENT_FSP_ERROR_LOG_LINK (
    GLOBAL_EVENT_FSP_ERROR_LOG_LINK_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GLOBAL_EVENT_ID INTEGER REFERENCES GLOBAL_EVENTS(GLOBAL_EVENT_ID),
    FSP_ERROR_LOG INTEGER REFERENCES PNODES_FSP_ERROR_LOGS(ERROR_LOG_ID)
);

CREATE TABLE GLOBAL_EVENT_ACCESS_POLICY_LINK (
    GLOBAL_EVENT_ACCESS_POLICY_LINK_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GLOBAL_EVENT_ID INTEGER REFERENCES GLOBAL_EVENTS(GLOBAL_EVENT_ID),
    PGRID_ACCESS_POLICY_ID INTEGER REFERENCES PGRID_ACCESS_POLICIES(access_policy_id)
);

CREATE TABLE GLOBAL_EVENT_TARGET_USER_LINK (
    GLOBAL_EVENT_TARGET_USER_LINK_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GLOBAL_EVENT_ID INTEGER REFERENCES GLOBAL_EVENTS(GLOBAL_EVENT_ID),
    TARGET_USER_ID INTEGER REFERENCES USERS(USER_ID),
    ACKNOWLEDGED_AT TIMESTAMP DEFAULT NULL,
    RESOLVED_AT TIMESTAMP DEFAULT NULL
);

CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GLOBAL_EVENT_ID INTEGER REFERENCES GLOBAL_EVENTS(GLOBAL_EVENT_ID)
);