CREATE OR REPLACE FUNCTION FN_GET_POWERENVDATABASE_SIZE()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        RETURN (SELECT pg_size_pretty FROM pg_size_pretty(pg_database_size('POWERENV-POWERDB')));
    END;
$$;

CREATE OR REPLACE FUNCTION FN_GET_FULL_USER_NAME (
    _FIRST_NAME VARCHAR,
    _LAST_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE plpgsql
AS $$
    DECLARE
    BEGIN
        RETURN _FIRST_NAME || ' ' || _LAST_NAME;
    END;
$$;