CREATE OR REPLACE VIEW VW_EVENTS_INFO AS
    SELECT GLOBAL_EVENTS.GLOBAL_EVENT_ID,
           GLOBAL_EVENTS.GLOBAL_EVENT_SEVERITY_LEVEL_ID,
           GLOBAL_EVENT_SEVERITY.GLOBAL_EVENT_SEVERITY_NAME,
           GLOBAL_EVENTS.GLOBAL_EVENT_TITLE,
           GLOBAL_EVENTS.GLOBAL_EVENT_DESCRIPTION,
           GLOBAL_EVENTS.GLOBAL_EVENT_TRIGGERED_AT,
           USERS.USER_ID,
           FN_GET_FULL_USER_NAME(USERS.USER_FIRST_NAME, USERS.USER_LAST_NAME) AS EVENT_TARGET_USERNAME,
           COALESCE(GLOBAL_EVENT_TARGET_USER_LINK.ACKNOWLEDGED_AT, '1-1-1 0:0:0.0000') AS ACKNOWLEDGED_AT,
           COALESCE(GLOBAL_EVENT_TARGET_USER_LINK.RESOLVED_AT, '1-1-1 0:0:0.0000') AS RESOLVED_AT
    FROM GLOBAL_EVENT_TARGET_USER_LINK
        INNER JOIN GLOBAL_EVENTS ON GLOBAL_EVENT_TARGET_USER_LINK.global_event_id = GLOBAL_EVENTS.global_event_id
        INNER JOIN USERS ON GLOBAL_EVENT_TARGET_USER_LINK.target_user_id = USERS.user_id
        INNER JOIN GLOBAL_EVENT_SEVERITY ON GLOBAL_EVENTS.GLOBAL_EVENT_SEVERITY_LEVEL_ID = GLOBAL_EVENT_SEVERITY.GLOBAL_EVENT_SEVERITY_ID;